<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SiteNavigationSeeder extends Seeder
{
	/**
	 * Run the database seeds.
	 *
	 * @return void
	 */
	public function run()
	{
		$siteNavigations = [
			[
				'menu_name' => 'Top Header Menu',
				'created_at' => now(),
				'updated_at' => now(),
				'navigation_items' => [
					[
						'id' => '1',
						'menu_label' => 'Administrative Body',
						'link' => '/administrative',
						'page_id' => '',
						'parent_id' => '',
						'css_class' => '',
						'css_id' => '',
						'menu_order' => '',
						'created_at' => now(),
						'updated_at' => now(),
					],
					[
						'id' => '2',
						'menu_label' => 'Teacher',
						'link' => '/teacher',
						'page_id' => '',
						'parent_id' => '',
						'css_class' => '',
						'css_id' => '',
						'menu_order' => '',
						'created_at' => now(),
						'updated_at' => now(),
					],
					[
						'id' => '3',
						'menu_label' => 'Departmental Staff Information',
						'link' => '/staff',
						'page_id' => '',
						'parent_id' => '',
						'css_class' => '',
						'css_id' => '',
						'menu_order' => '',
						'created_at' => now(),
						'updated_at' => now(),
					],
					[
						'id' => '4',
						'menu_label' => 'Students',
						'link' => '/login/type/student',
						'page_id' => '',
						'parent_id' => '',
						'css_class' => '',
						'css_id' => '',
						'menu_order' => '',
						'created_at' => now(),
						'updated_at' => now(),
					],
					[
						'id' => '5',
						'menu_label' => 'Book List',
						'link' => '/booklist',
						'page_id' => '',
						'parent_id' => '',
						'css_class' => '',
						'css_id' => '',
						'menu_order' => '',
						'created_at' => now(),
						'updated_at' => now(),
					]
				]
			],
			[
				'menu_name' => 'Header Menu',
				'created_at' => now(),
				'updated_at' => now(),
				'navigation_items' => [
					[
						'id' => '6',
						'menu_label' => 'Home',
						'link' => '/',
						'page_id' => '',
						'parent_id' => '',
						'css_class' => '',
						'css_id' => '',
						'menu_order' => '',
						'created_at' => now(),
						'updated_at' => now(),
					],
					[
						'id' => '7',
						'menu_label' => 'About Us',
						'link' => '#',
						'page_id' => '',
						'parent_id' => '',
						'css_class' => '',
						'css_id' => '',
						'menu_order' => '',
						'created_at' => now(),
						'updated_at' => now(),
					],
					[
						'id' => '8',
						'menu_label' => 'Principal\'s Message',
						'link' => '/page/principal-speech',
						'page_id' => '',
						'parent_id' => '7',
						'css_class' => '',
						'css_id' => '',
						'menu_order' => '',
						'created_at' => now(),
						'updated_at' => now(),
					],
					[
						'id' => '9',
						'menu_label' => 'History of NDCM',
						'link' => '/page/history',
						'page_id' => '',
						'parent_id' => '7',
						'css_class' => '',
						'css_id' => '',
						'menu_order' => '',
						'created_at' => now(),
						'updated_at' => now(),
					],
					[
						'id' => '10',
						'menu_label' => 'Explanation of Nomenclature',
						'link' => '/page/explanation-nomenclature',
						'page_id' => '',
						'parent_id' => '7',
						'css_class' => '',
						'css_id' => '',
						'menu_order' => '',
						'created_at' => now(),
						'updated_at' => now(),
					],
					[
						'id' => '11',
						'menu_label' => 'Vision',
						'link' => '/page/vision',
						'page_id' => '',
						'parent_id' => '7',
						'css_class' => '',
						'css_id' => '',
						'menu_order' => '',
						'created_at' => now(),
						'updated_at' => now(),
					],
					[
						'id' => '12',
						'menu_label' => 'Mission',
						'link' => '/page/mission',
						'page_id' => '',
						'parent_id' => '7',
						'css_class' => '',
						'css_id' => '',
						'menu_order' => '',
						'created_at' => now(),
						'updated_at' => now(),
					],
					[
						'id' => '13',
						'menu_label' => 'Objective',
						'link' => '/page/objective',
						'page_id' => '',
						'parent_id' => '7',
						'css_class' => '',
						'css_id' => '',
						'menu_order' => '',
						'created_at' => now(),
						'updated_at' => now(),
					],
					[
						'id' => '14',
						'menu_label' => 'Goal',
						'link' => '/page/goal',
						'page_id' => '',
						'parent_id' => '7',
						'css_class' => '',
						'css_id' => '',
						'menu_order' => '',
						'created_at' => now(),
						'updated_at' => now(),
					],
					[
						'id' => '15',
						'menu_label' => 'Motto',
						'link' => '/page/motto',
						'page_id' => '',
						'parent_id' => '7',
						'css_class' => '',
						'css_id' => '',
						'menu_order' => '',
						'created_at' => now(),
						'updated_at' => now(),
					],
					[
						'id' => '16',
						'menu_label' => 'Academic',
						'link' => '#',
						'page_id' => '',
						'parent_id' => '',
						'css_class' => '',
						'css_id' => '',
						'menu_order' => '',
						'created_at' => now(),
						'updated_at' => now(),
					],
					[
						'id' => '17',
						'menu_label' => 'Admission Information',
						'link' => '/student-online-registration',
						'page_id' => '',
						'parent_id' => '16',
						'css_class' => '',
						'css_id' => '',
						'menu_order' => '',
						'created_at' => now(),
						'updated_at' => now(),
					],
					[
						'id' => '18',
						'menu_label' => 'Book List',
						'link' => '/booklist',
						'page_id' => '',
						'parent_id' => '16',
						'css_class' => '',
						'css_id' => '',
						'menu_order' => '',
						'created_at' => now(),
						'updated_at' => now(),
					],
					[
						'id' => '19',
						'menu_label' => 'Academic Achievement',
						'link' => '/page/academic-achievement',
						'page_id' => '',
						'parent_id' => '16',
						'css_class' => '',
						'css_id' => '',
						'menu_order' => '',
						'created_at' => now(),
						'updated_at' => now(),
					],
					[
						'id' => '20',
						'menu_label' => 'Academic Facilities',
						'link' => '/page/academic-facilities',
						'page_id' => '',
						'parent_id' => '16',
						'css_class' => '',
						'css_id' => '',
						'menu_order' => '',
						'created_at' => now(),
						'updated_at' => now(),
					],
					[
						'id' => '21',
						'menu_label' => 'Co Curriculums',
						'link' => '#',
						'page_id' => '',
						'parent_id' => '',
						'css_class' => '',
						'css_id' => '',
						'menu_order' => '',
						'created_at' => now(),
						'updated_at' => now(),
					],
					[
						'id' => '22',
						'menu_label' => 'Debating Club',
						'link' => '/club/debating-club',
						'page_id' => '',
						'parent_id' => '21',
						'css_class' => '',
						'css_id' => '',
						'menu_order' => '',
						'created_at' => now(),
						'updated_at' => now(),
					],
					[
						'id' => '23',
						'menu_label' => 'Cultural Club',
						'link' => '/club/cultural-club',
						'page_id' => '',
						'parent_id' => '21',
						'css_class' => '',
						'css_id' => '',
						'menu_order' => '',
						'created_at' => now(),
						'updated_at' => now(),
					],
					[
						'id' => '24',
						'menu_label' => 'Science Club',
						'link' => '/club/science-club',
						'page_id' => '',
						'parent_id' => '21',
						'css_class' => '',
						'css_id' => '',
						'menu_order' => '',
						'created_at' => now(),
						'updated_at' => now(),
					],

					[
						'id' => '25',
						'menu_label' => 'Business Club',
						'link' => '/club/business-club',
						'page_id' => '',
						'parent_id' => '21',
						'css_class' => '',
						'css_id' => '',
						'menu_order' => '',
						'created_at' => now(),
						'updated_at' => now(),
					],
					[
						'id' => '26',
						'menu_label' => 'Humanities Club',
						'link' => '/club/humanities-club',
						'page_id' => '',
						'parent_id' => '21',
						'css_class' => '',
						'css_id' => '',
						'menu_order' => '',
						'created_at' => now(),
						'updated_at' => now(),
					],
					[
						'id' => '27',
						'menu_label' => 'English Language and Research Club',
						'link' => '/club/english-research-club',
						'page_id' => '',
						'parent_id' => '21',
						'css_class' => '',
						'css_id' => '',
						'menu_order' => '',
						'created_at' => now(),
						'updated_at' => now(),
					],
					[
						'id' => '28',
						'menu_label' => 'Nature and Literature Club',
						'link' => '/club/nature-literature-club',
						'page_id' => '',
						'parent_id' => '21',
						'css_class' => '',
						'css_id' => '',
						'menu_order' => '',
						'created_at' => now(),
						'updated_at' => now(),
					],
					[
						'id' => '29',
						'menu_label' => 'Photography and Media Club',
						'link' => '/club/photography-media-club',
						'page_id' => '',
						'parent_id' => '21',
						'css_class' => '',
						'css_id' => '',
						'menu_order' => '',
						'created_at' => now(),
						'updated_at' => now(),
					],
					[
						'id' => '30',
						'menu_label' => 'Math Club',
						'link' => '/club/math-club',
						'page_id' => '',
						'parent_id' => '21',
						'css_class' => '',
						'css_id' => '',
						'menu_order' => '',
						'created_at' => now(),
						'updated_at' => now(),
					],
					[
						'id' => '31',
						'menu_label' => 'Nattyo Club',
						'link' => '/club/nattyo-club',
						'page_id' => '',
						'parent_id' => '21',
						'css_class' => '',
						'css_id' => '',
						'menu_order' => '',
						'created_at' => now(),
						'updated_at' => now(),
					],
					[
						'id' => '32',
						'menu_label' => 'ICT Club',
						'link' => '/club/ict-club',
						'page_id' => '',
						'parent_id' => '21',
						'css_class' => '',
						'css_id' => '',
						'menu_order' => '',
						'created_at' => now(),
						'updated_at' => now(),
					],

					[
						'id' => '33',
						'menu_label' => 'News and Events',
						'link' => '#',
						'page_id' => '',
						'parent_id' => '',
						'css_class' => '',
						'css_id' => '',
						'menu_order' => '',
						'created_at' => now(),
						'updated_at' => now(),
					],
					[
						'id' => '34',
						'menu_label' => 'Recent Posts',
						'link' => '/all-notices',
						'page_id' => '',
						'parent_id' => '33',
						'css_class' => '',
						'css_id' => '',
						'menu_order' => '',
						'created_at' => now(),
						'updated_at' => now(),
					],
					[
						'id' => '35',
						'menu_label' => 'Archives',
						'link' => '/archive-news',
						'page_id' => '',
						'parent_id' => '33',
						'css_class' => '',
						'css_id' => '',
						'menu_order' => '',
						'created_at' => now(),
						'updated_at' => now(),
					],
					[
						'id' => '36',
						'menu_label' => 'Gallery',
						'link' => '#',
						'page_id' => '',
						'parent_id' => ' ',
						'css_class' => '',
						'css_id' => '',
						'menu_order' => '',
						'created_at' => now(),
						'updated_at' => now(),
					],
					[
						'id' => '37',
						'menu_label' => 'Image Gallery',
						'link' => '/page/image-gallery',
						'page_id' => '',
						'parent_id' => '36',
						'css_class' => '',
						'css_id' => '',
						'menu_order' => '',
						'created_at' => now(),
						'updated_at' => now(),
					],
					[
						'id' => '38',
						'menu_label' => 'Video Gallery',
						'link' => '/page/video-gallery',
						'page_id' => '',
						'parent_id' => '36',
						'css_class' => '',
						'css_id' => '',
						'menu_order' => '',
						'created_at' => now(),
						'updated_at' => now(),
					],
					[
						'id' => '39',
						'menu_label' => 'Notice',
						'link' => '/all-notices',
						'page_id' => '',
						'parent_id' => '',
						'css_class' => '',
						'css_id' => '',
						'menu_order' => '',
						'created_at' => now(),
						'updated_at' => now(),
					],
					[
						'id' => '40',
						'menu_label' => 'Contact',
						'link' => '/contact-us',
						'page_id' => '',
						'parent_id' => '',
						'css_class' => '',
						'css_id' => '',
						'menu_order' => '',
						'created_at' => now(),
						'updated_at' => now(),
					],

				]
			],
			[
				'menu_name' => 'Footer Menu',
				'created_at' => now(),
				'updated_at' => now(),
				'navigation_items' => [
					[
						'id' => '41',
						'menu_label' => 'Important Links',
						'link' => '3',
						'page_id' => '',
						'parent_id' => '',
						'css_class' => '',
						'css_id' => '',
						'menu_order' => '',
						'created_at' => now(),
						'updated_at' => now(),
					],
					[
						'id' => '42',
						'menu_label' => 'History of NDCM',
						'link' => '/page/history',
						'page_id' => '',
						'parent_id' => '41',
						'css_class' => '',
						'css_id' => '',
						'menu_order' => '',
						'created_at' => now(),
						'updated_at' => now(),
					],
					[
						'id' => '43',
						'menu_label' => 'Class Routine',
						'link' => '/page/class-routine',
						'page_id' => '',
						'parent_id' => '41',
						'css_class' => '',
						'css_id' => '',
						'menu_order' => '',
						'created_at' => now(),
						'updated_at' => now(),
					],
					[
						'id' => '44',
						'menu_label' => 'Teacher',
						'link' => '/teacher',
						'page_id' => '',
						'parent_id' => '41',
						'css_class' => '',
						'css_id' => '',
						'menu_order' => '',
						'created_at' => now(),
						'updated_at' => now(),
					],
					[
						'id' => '45',
						'menu_label' => 'Contact us',
						'link' => '/contact-us',
						'page_id' => '',
						'parent_id' => '41',
						'css_class' => '',
						'css_id' => '',
						'menu_order' => '',
						'created_at' => now(),
						'updated_at' => now(),
					],
					[
						'id' => '46',
						'menu_label' => 'Office staff',
						'link' => '/staff',
						'page_id' => '',
						'parent_id' => '41',
						'css_class' => '',
						'css_id' => '',
						'menu_order' => '',
						'created_at' => now(),
						'updated_at' => now(),
					],
					[
						'id' => '47',
						'menu_label' => '',
						'link' => '#',
						'page_id' => '',
						'parent_id' => '',
						'css_class' => '',
						'css_id' => '',
						'menu_order' => '',
						'created_at' => now(),
						'updated_at' => now(),
					],
					[
						'id' => '48',
						'menu_label' => 'Principal\'s Message',
						'link' => '/page/principal-speech',
						'page_id' => '',
						'parent_id' => '47',
						'css_class' => '',
						'css_id' => '',
						'menu_order' => '',
						'created_at' => now(),
						'updated_at' => now(),
					],
					[
						'id' => '49',
						'menu_label' => 'Health Care',
						'link' => '/page/health-care',
						'page_id' => '',
						'parent_id' => '47',
						'css_class' => '',
						'css_id' => '',
						'menu_order' => '',
						'created_at' => now(),
						'updated_at' => now(),
					],
					[
						'id' => '50',
						'menu_label' => 'Notice',
						'link' => '/all-notices',
						'page_id' => '',
						'parent_id' => '47',
						'css_class' => '',
						'css_id' => '',
						'menu_order' => '',
						'created_at' => now(),
						'updated_at' => now(),
					],
					[
						'id' => '51',
						'menu_label' => 'Library',
						'link' => '/page/library',
						'page_id' => '',
						'parent_id' => '47',
						'css_class' => '',
						'css_id' => '',
						'menu_order' => '',
						'created_at' => now(),
						'updated_at' => now(),
					],
					[
						'id' => '52',
						'menu_label' => 'Recent Posts',
						'link' => '/all-notices',
						'page_id' => '',
						'parent_id' => '47',
						'css_class' => '',
						'css_id' => '',
						'menu_order' => '',
						'created_at' => now(),
						'updated_at' => now(),
					],
					[
						'id' => '53',
						'menu_label' => 'Teacher Login',
						'link' => '/login/type/teacher',
						'page_id' => '',
						'parent_id' => '47',
						'css_class' => '',
						'css_id' => '',
						'menu_order' => '',
						'created_at' => now(),
						'updated_at' => now(),
					],
					[
						'id' => '54',
						'menu_label' => 'Student Login',
						'link' => '/login/type/student',
						'page_id' => '',
						'parent_id' => '47',
						'css_class' => '',
						'css_id' => '',
						'menu_order' => '',
						'created_at' => now(),
						'updated_at' => now(),
					],
					[
						'id' => '55',
						'menu_label' => '',
						'link' => '#',
						'page_id' => '',
						'parent_id' => '',
						'css_class' => '',
						'css_id' => '',
						'menu_order' => '',
						'created_at' => now(),
						'updated_at' => now(),
					],
					[
						'id' => '56',
						'menu_label' => 'Notre Dame University',
						'link' => 'https://ndub.edu.bd/',
						'page_id' => '',
						'parent_id' => '55',
						'css_class' => '',
						'css_id' => '',
						'menu_order' => '',
						'created_at' => now(),
						'updated_at' => now(),
					],
					[
						'id' => '57',
						'menu_label' => 'Notre Dame college',
						'link' => 'http://ndc.edu.bd/',
						'page_id' => '',
						'parent_id' => '55',
						'css_class' => '',
						'css_id' => '',
						'menu_order' => '',
						'created_at' => now(),
						'updated_at' => now(),
					],
					[
						'id' => '58',
						'menu_label' => 'Shikkhok Bataon',
						'link' => 'https://teachers.gov.bd/',
						'page_id' => '',
						'parent_id' => '55',
						'css_class' => '',
						'css_id' => '',
						'menu_order' => '',
						'created_at' => now(),
						'updated_at' => now(),
					],
					[
						'id' => '59',
						'menu_label' => 'National Web Portal',
						'link' => 'https://bangladesh.gov.bd/index.php',
						'page_id' => '',
						'parent_id' => '55',
						'css_class' => '',
						'css_id' => '',
						'menu_order' => '',
						'created_at' => now(),
						'updated_at' => now(),
					],
					[
						'id' => '60',
						'menu_label' => 'Ministry of Education',
						'link' => 'https://moedu.gov.bd/',
						'page_id' => '',
						'parent_id' => '55',
						'css_class' => '',
						'css_id' => '',
						'menu_order' => '',
						'created_at' => now(),
						'updated_at' => now(),
					],

				]
			],
		];

		foreach ($siteNavigations as $navigation) {
			$navigationItems = $navigation['navigation_items'];
			unset($navigation['navigation_items']);
			$navigationId = DB::table('site_navigations')->insertGetId($navigation);

			foreach ($navigationItems as $navigationItem) {
				$navigationItem['navigation_id'] = $navigationId;
				DB::table('site_navigation_items')->insert($navigationItem);
			}
		}
	}
}
