<?php

namespace Database\Seeders;

use App\Staff;
use App\UserPayroll;
use App\SalaryHeadUserPayroll;
use Illuminate\Database\Seeder;
use App\Services\SalaryHeadService;

class StaffSeeder extends Seeder
{
    public function __construct(
        private readonly SalaryHeadService $salaryHead
    ) {
    }

    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $staffData = [
            // Administration
            [
                'id' => 1,
                'user_id' => 101,
                'department_id' => 1,
                'name' => 'Fr. Thadeus Hembrom, CSC',
                'designation' => 'Principal',
                'gender' => 'Male',
                'phone' => '01715759667',
                'sl' => 1,
            ],
            [
                'id' => 2,
                'user_id' => 102,
                'department_id' => 1,
                'name' => 'Fr. Hubert Palma, CSC',
                'designation' => 'Office Administrator',
                'gender' => 'Male',
                'phone' => '01720996644',
                'sl' => 2,
            ],
            [
                'id' => 3,
                'user_id' => 103,
                'department_id' => 1,
                'name' => 'Fr. Gracy D`Rozario, CSC',
                'designation' => 'Assistant Director of Guidance',
                'gender' => 'Male',
                'phone' => '01912428558',
                'sl' => 3,
            ],
            [
                'id' => 4,
                'user_id' => 104,
                'department_id' => 1,
                'name' => 'Mr. Theophil Hajong',
                'designation' => 'Administrative Secretary',
                'gender' => 'Male',
                'phone' => '01711591073',
                'sl' => 4,
            ],
            [
                'id' => 5,
                'user_id' => 105,
                'department_id' => 1,
                'name' => 'Mr. Racksy B Rozario',
                'designation' => 'Office Admin - Office Coordinator',
                'gender' => 'Male',
                'phone' => '01827184022',
                'sl' => 5,
            ],

            // Principal Office
            [
                'id' => 6,
                'user_id' => 106,
                'department_id' => 1,
                'name' => 'Mr. Theophil Hajong',
                'designation' => 'Administrative Secretary',
                'gender' => 'Male',
                'phone' => '01711591073',
                'sl' => 6,
            ],
            [
                'id' => 7,
                'user_id' => 107,
                'department_id' => 1,
                'name' => 'Mr. Jyoti Francis Dawa',
                'designation' => 'P.A to the Principal',
                'gender' => 'Male',
                'phone' => '01782495184',
                'sl' => 7,
            ],

            // Academic/Main Office
            [
                'id' => 8,
                'user_id' => 108,
                'department_id' => 1,
                'name' => 'Fr. Hubert Palma, CSC',
                'designation' => 'Office In-charge',
                'gender' => 'Male',
                'phone' => '01720996644',
                'sl' => 8,
            ],
            [
                'id' => 9,
                'user_id' => 109,
                'department_id' => 1,
                'name' => 'Mr. Racksy B Rozario',
                'designation' => 'Office Admin - Office Coordinator',
                'gender' => 'Male',
                'phone' => '01827184022',
                'sl' => 9,
            ],
            [
                'id' => 10,
                'user_id' => 110,
                'department_id' => 1,
                'name' => 'Mr. Ringku Joseph Cruze',
                'designation' => 'Office Admin - Academic',
                'gender' => 'Male',
                'phone' => '01855846316',
                'sl' => 10,
            ],
            [
                'id' => 11,
                'user_id' => 111,
                'department_id' => 1,
                'name' => 'Mr. Hubert Mree	Office',
                'designation' => 'Office Assistant - Academic',
                'gender' => 'Male',
                'phone' => '01724642328',
                'sl' => 11,
            ],
            [
                'id' => 12,
                'user_id' => 112,
                'department_id' => 1,
                'name' => 'Mrs. Monju Simsang',
                'designation' => 'Office Assistant - Academic',
                'gender' => 'Male',
                'phone' => '01789933137',
                'sl' => 12,
            ],
            [
                'id' => 13,
                'user_id' => 113,
                'department_id' => 1,
                'name' => 'Ms. Aulovi Chiran',
                'designation' => 'Office Assistant - Academic',
                'gender' => 'Male',
                'phone' => '01793746303',
                'sl' => 13,
            ],
            [
                'id' => 14,
                'user_id' => 114,
                'department_id' => 1,
                'name' => 'Mr. Chapal Rozario',
                'designation' => 'Office Assistant - Academic',
                'gender' => 'Male',
                'phone' => '01965173746',
                'sl' => 14,
            ],
            [
                'id' => 15,
                'user_id' => 115,
                'department_id' => 1,
                'name' => 'Mr. Jasengh Drong',
                'designation' => 'Office Peon',
                'gender' => 'Male',
                'phone' => '01850721872',
                'sl' => 15,
            ],

            // Exam
            [
                'id' => 16,
                'user_id' => 116,
                'department_id' => 1,
                'name' => 'Fr. Gracy D`Rozario, CSC',
                'designation' => 'Office In-charge',
                'gender' => 'Male',
                'phone' => '01912428558',
                'sl' => 16,
            ],
            [
                'id' => 17,
                'user_id' => 117,
                'department_id' => 1,
                'name' => 'Mr. Rony Sen Gupta',
                'designation' => 'Office Admin - Office Coordinator',
                'gender' => 'Male',
                'phone' => '01710763447',
                'sl' => 17,
            ],
            [
                'id' => 18,
                'user_id' => 118,
                'department_id' => 1,
                'name' => 'Mr. Jony Kubi',
                'designation' => 'Office Assistant',
                'gender' => 'Male',
                'phone' => '01759618458',
                'sl' => 18,
            ],
            [
                'id' => 19,
                'user_id' => 119,
                'department_id' => 1,
                'name' => 'Mr. Subroto Das',
                'designation' => 'Office Assistant',
                'gender' => 'Male',
                'phone' => '01704472671',
                'sl' => 19,
            ],

            // Account
            [
                'id' => 20,
                'user_id' => 120,
                'department_id' => 1,
                'name' => 'Fr. Thadeus Hembrom, CSC',
                'designation' => 'Office In-charge',
                'gender' => 'Male',
                'phone' => '01715759667',
                'sl' => 20,
            ],
            [
                'id' => 21,
                'user_id' => 121,
                'department_id' => 1,
                'name' => 'Mr. Redcliffe Dibra',
                'designation' => 'Office In-charge',
                'gender' => 'Male',
                'phone' => '01921129770',
                'sl' => 21,
            ],
            [
                'id' => 22,
                'user_id' => 122,
                'department_id' => 1,
                'name' => 'Mr. Toney Pereira',
                'designation' => 'Office In-charge',
                'gender' => 'Male',
                'phone' => '01682613805',
                'sl' => 22,
            ],
            [
                'id' => 23,
                'user_id' => 123,
                'department_id' => 1,
                'name' => 'Mr. Tobias Murmu',
                'designation' => 'Office In-charge',
                'gender' => 'Male',
                'phone' => '01722188269',
                'sl' => 23,
            ],

            // Guidance
            [
                'id' => 24,
                'user_id' => 124,
                'department_id' => 1,
                'name' => 'Fr. Hubert Palma, CSC',
                'designation' => 'Director of Guidance',
                'gender' => 'Male',
                'phone' => '01720996644',
                'sl' => 24,
            ],
            [
                'id' => 25,
                'user_id' => 125,
                'department_id' => 1,
                'name' => 'Fr. Isubious Gracy D`Rozario, CSC',
                'designation' => 'Assistant Director of Guidance',
                'gender' => 'Male',
                'phone' => '01912428558',
                'sl' => 25,
            ],

            // Information & Technology
            [
                'id' => 26,
                'user_id' => 126,
                'department_id' => 1,
                'name' => 'Fr. Hubert Palma, CSC',
                'designation' => 'Office In-charge',
                'gender' => 'Male',
                'phone' => '01720996644',
                'sl' => 26,
            ],
            [
                'id' => 27,
                'user_id' => 127,
                'department_id' => 1,
                'name' => 'Mr. Sabuj Mrong	Office',
                'designation' => 'Admin (IT)',
                'gender' => 'Male',
                'phone' => '01701765423',
                'sl' => 27,
            ],
            [
                'id' => 28,
                'user_id' => 128,
                'department_id' => 1,
                'name' => 'Mr. Partho Rodrigues',
                'designation' => 'Assistant of IT Office & Computer Lab',
                'gender' => 'Male',
                'phone' => '01731119052',
                'sl' => 28,
            ],

            // Laboratories
            [
                'id' => 29,
                'user_id' => 129,
                'department_id' => 1,
                'name' => 'Fr. Gracy D`Rozario, CSC',
                'designation' => 'Lab Coordinator',
                'gender' => 'Male',
                'phone' => '01912428558',
                'sl' => 29,
            ],
            [
                'id' => 30,
                'user_id' => 130,
                'department_id' => 1,
                'name' => 'Mr. Samuel Shongkor Roy Shanto',
                'designation' => 'Biology Lab Assistant',
                'gender' => 'Male',
                'phone' => '01780918233',
                'sl' => 30,
            ],
            [
                'id' => 31,
                'user_id' => 131,
                'department_id' => 1,
                'name' => 'Mr. Diparson Sangma',
                'designation' => 'Physics Lab Assistant',
                'gender' => 'Male',
                'phone' => '01739069000',
                'sl' => 31,
            ],
            [
                'id' => 32,
                'user_id' => 132,
                'department_id' => 1,
                'name' => 'Mr. Timol Chambugong',
                'designation' => 'Chemistry Lab Assistant',
                'gender' => 'Male',
                'phone' => '01992913000',
                'sl' => 32,
            ],

            // Library
            [
                'id' => 33,
                'user_id' => 133,
                'department_id' => 1,
                'name' => 'Fr. Thadeus Hembrom, CSC',
                'designation' => 'Office In-Charge',
                'gender' => 'Male',
                'phone' => '01715759667',
                'sl' => 33,
            ],
            [
                'id' => 34,
                'user_id' => 134,
                'department_id' => 1,
                'name' => 'Mrs. Afia Khatun',
                'designation' => 'Assistant Librarian',
                'gender' => 'Male',
                'phone' => '01734852182',
                'sl' => 34,
            ],
            [
                'id' => 35,
                'user_id' => 135,
                'department_id' => 1,
                'name' => 'Mrs. Tonni Rozlin Dio',
                'designation' => 'Office Assistant - Library',
                'gender' => 'Male',
                'phone' => '01911749538',
                'sl' => 35,
            ],

            // Store Room
            [
                'id' => 36,
                'user_id' => 136,
                'department_id' => 1,
                'name' => 'Fr. Hubert Palma, CSC',
                'designation' => 'Storeroom In-Charge',
                'gender' => 'Male',
                'phone' => '01720996644',
                'sl' => 36,
            ],
            [
                'id' => 37,
                'user_id' => 137,
                'department_id' => 1,
                'name' => 'Mrs. Sreeta Kisku',
                'designation' => 'Storekeeper',
                'gender' => 'Male',
                'phone' => '01773813392',
                'sl' => 37,
            ],

            // Maintenance
            [
                'id' => 38,
                'user_id' => 138,
                'department_id' => 1,
                'name' => 'Md. Mustofa Kamal',
                'designation' => 'Manager of Maintenance',
                'gender' => 'Male',
                'phone' => '01916311010',
                'sl' => 38,
            ],
            [
                'id' => 39,
                'user_id' => 139,
                'department_id' => 1,
                'name' => 'Md. Arshad Hossain',
                'designation' => 'Assistant Director of Maintenance',
                'gender' => 'Male',
                'phone' => '01797343925',
                'sl' => 39,
            ],
            [
                'id' => 40,
                'user_id' => 140,
                'department_id' => 1,
                'name' => 'Md. Masud Alam',
                'designation' => 'Maintenance Assistant',
                'gender' => 'Male',
                'phone' => '01904450502',
                'sl' => 40,
            ],
            [
                'id' => 41,
                'user_id' => 141,
                'department_id' => 1,
                'name' => 'Md. Shamsul Huda Rasel',
                'designation' => 'Electrician',
                'gender' => 'Male',
                'phone' => '01729413268',
                'sl' => 41,
            ],
            [
                'id' => 42,
                'user_id' => 142,
                'department_id' => 1,
                'name' => 'Mr. Sentu Chisim',
                'designation' => 'Driver',
                'gender' => 'Male',
                'phone' => '01764156658',
                'sl' => 42,
            ],
            [
                'id' => 43,
                'user_id' => 143,
                'department_id' => 1,
                'name' => 'Mr. Bimol Costa	Cook',
                'designation' => 'Quinlivan House',
                'gender' => 'Male',
                'phone' => '01718809332',
                'sl' => 43,
            ],
            [
                'id' => 44,
                'user_id' => 144,
                'department_id' => 1,
                'name' => 'Mr. Rosan Basra	Janitor',
                'designation' => 'Quinlivan House',
                'gender' => 'Male',
                'phone' => '01939363138',
                'sl' => 44,
            ],
            [
                'id' => 45,
                'user_id' => 145,
                'department_id' => 1,
                'name' => 'Mr. Nibesh Mankhin',
                'designation' => 'Gardener',
                'gender' => 'Male',
                'phone' => '01719980747',
                'sl' => 45,
            ],
            [
                'id' => 46,
                'user_id' => 146,
                'department_id' => 1,
                'name' => 'Md. Alom Mia',
                'designation' => 'Gardener',
                'gender' => 'Male',
                'phone' => '01721973869',
                'sl' => 46,
            ],
            [
                'id' => 47,
                'user_id' => 147,
                'department_id' => 1,
                'name' => 'Mr. Manik Chonra Sotra Dor',
                'designation' => 'Carpenter',
                'gender' => 'Male',
                'phone' => '01854777113',
                'sl' => 47,
            ],
            [
                'id' => 48,
                'user_id' => 148,
                'department_id' => 1,
                'name' => 'Md. Ashraful Islam',
                'designation' => 'Security Guard',
                'gender' => 'Male',
                'phone' => '01938083631',
                'sl' => 48,
            ],
            [
                'id' => 49,
                'user_id' => 149,
                'department_id' => 1,
                'name' => 'Mr. Mithun Gomes',
                'designation' => 'Security Guard',
                'gender' => 'Male',
                'phone' => '01957927789',
                'sl' => 49,
            ],
            [
                'id' => 50,
                'user_id' => 150,
                'department_id' => 1,
                'name' => 'Mr. Liton Chiran',
                'designation' => 'Security Guard',
                'gender' => 'Male',
                'phone' => '01776268991',
                'sl' => 50,
            ],
            [
                'id' => 51,
                'user_id' => 151,
                'department_id' => 1,
                'name' => 'Mr. Polinus Kama',
                'designation' => 'Security Guard',
                'gender' => 'Male',
                'phone' => '01745755074',
                'sl' => 51,
            ],
            [
                'id' => 52,
                'user_id' => 152,
                'department_id' => 1,
                'name' => 'Mr. Bidra Chambugong',
                'designation' => 'Security Guard',
                'gender' => 'Male',
                'phone' => '01304378616',
                'sl' => 52,
            ],
            [
                'id' => 53,
                'user_id' => 153,
                'department_id' => 1,
                'name' => 'Mr. Hilion Mankhin',
                'designation' => 'Janitor',
                'gender' => 'Male',
                'phone' => '01833081839',
                'sl' => 53,
            ],
            [
                'id' => 54,
                'user_id' => 154,
                'department_id' => 1,
                'name' => 'Mr. Badal Mrong	Janitor',
                'designation' => 'Janitor',
                'gender' => 'Male',
                'phone' => '01859099717',
                'sl' => 54,
            ],
            [
                'id' => 55,
                'user_id' => 155,
                'department_id' => 1,
                'name' => 'Mr. Hridoy Gomes',
                'designation' => 'Janitor',
                'gender' => 'Male',
                'phone' => '01317090599',
                'sl' => 55,
            ],
            [
                'id' => 56,
                'user_id' => 156,
                'department_id' => 1,
                'name' => 'Fr. Hubert Palma, CSC',
                'designation' => 'Janitor',
                'gender' => 'Male',
                'phone' => '01720996644',
                'sl' => 56,
            ],

            // Bookstore
            [
                'id' => 57,
                'user_id' => 157,
                'department_id' => 1,
                'name' => 'Fr. Hubert Palma, CSC',
                'designation' => 'Bookstore In-charge',
                'gender' => 'Male',
                'phone' => '01720996644',
                'sl' => 57,
            ],
            [
                'id' => 58,
                'user_id' => 158,
                'department_id' => 1,
                'name' => 'Mr. Poritush Bonowari',
                'designation' => 'Bookstore Assistant',
                'gender' => 'Male',
                'phone' => '01719592157',
                'sl' => 58,
            ],

            // Student Work Program
            [
                'id' => 59,
                'user_id' => 159,
                'department_id' => 1,
                'name' => 'Fr. Gracy D`Rozario, CSC',
                'designation' => 'Work Program Director',
                'gender' => 'Male',
                'phone' => '01912428558',
                'sl' => 59,
            ],
            [
                'id' => 60,
                'user_id' => 160,
                'department_id' => 1,
                'name' => 'Mr. Liptu Chambugong',
                'designation' => 'In-charge',
                'gender' => 'Male',
                'phone' => '01739339970',
                'sl' => 60,
            ],
            [
                'id' => 61,
                'user_id' => 161,
                'department_id' => 1,
                'name' => 'Mr. Pankoj Chambugong',
                'designation' => 'Assistant Cook - Work Program',
                'gender' => 'Male',
                'phone' => '01980721277',
                'sl' => 61,
            ],
            [
                'id' => 62,
                'user_id' => 162,
                'department_id' => 1,
                'name' => 'Mr. Suidish Chisim',
                'designation' => 'Assistant Cook - Work Program',
                'gender' => 'Male',
                'phone' => '01759294100',
                'sl' => 62,
            ],


            // Maintenance
            [
                'id' => 63,
                'user_id' => 163,
                'department_id' => 1,
                'name' => 'Aoulovi',
                'designation' => 'Maintenance',
                'gender' => 'Male',
                'phone' => '01793746303',
                'sl' => 63,
            ],
            [
                'id' => 64,
                'user_id' => 164,
                'department_id' => 1,
                'name' => 'Timol',
                'designation' => 'Maintenance',
                'gender' => 'Male',
                'phone' => '01992913000',
                'sl' => 64,
            ],
            [
                'id' => 65,
                'user_id' => 165,
                'department_id' => 1,
                'name' => 'Tonni',
                'designation' => 'Maintenance',
                'gender' => 'Female',
                'phone' => '01915925228',
                'sl' => 65,
            ],
            [
                'id' => 66,
                'user_id' => 166,
                'department_id' => 1,
                'name' => 'Afia',
                'designation' => 'Maintenance',
                'gender' => 'Female',
                'phone' => '01734852182',
                'sl' => 66,
            ],
            [
                'id' => 67,
                'user_id' => 167,
                'department_id' => 1,
                'name' => 'Partho',
                'designation' => 'Maintenance',
                'gender' => 'Male',
                'phone' => '01329490800',
                'sl' => 67,
            ],
            [
                'id' => 68,
                'user_id' => 168,
                'department_id' => 1,
                'name' => 'Srita',
                'designation' => 'Maintenance',
                'gender' => 'Female',
                'phone' => '01784640376',
                'sl' => 68,
            ],
            [
                'id' => 69,
                'user_id' => 169,
                'department_id' => 1,
                'name' => 'Shanto',
                'designation' => 'Maintenance',
                'gender' => 'Female',
                'phone' => '01780918283',
                'sl' => 69,
            ],
            [
                'id' => 70,
                'user_id' => 170,
                'department_id' => 1,
                'name' => 'Monju',
                'designation' => 'Maintenance',
                'gender' => 'Male',
                'phone' => '01928722347',
                'sl' => 70,
            ],
            [
                'id' => 71,
                'user_id' => 171,
                'department_id' => 1,
                'name' => 'Chopol',
                'designation' => 'Maintenance',
                'gender' => 'Male',
                'phone' => '01749738005',
                'sl' => 71,
            ],
        ];

        foreach ($staffData as $data) {
            $staff = Staff::create($data);

            // if ($staff->save()) {
            //     $userPayroll = new UserPayroll([
            //         'user_id' => $data['user_id'],
            //         'net_salary' => 40,
            //         'current_due' => 10,
            //         'current_advance' => 5
            //     ]);
            //     $userPayroll->save();

            //     $salaryHeads = $this->salaryHead->getSalaryHeads();

            //     foreach ($salaryHeads as $salaryHead) {
            //         $salaryHeadUserPayroll = new SalaryHeadUserPayroll([
            //             'user_payroll_id' => $userPayroll->id,
            //             'salary_head_id' => $salaryHead->id,
            //             'amount' => 10,
            //         ]);
            //         $salaryHeadUserPayroll->save();
            //     }
            // }
        }
    }
}
